### ISSUE TITLE
could not build python package by setuptools

### ISSUE THREAD

**Issue by JULY5590** [gpufit/Gpufit#128]
while building gpufit in windows11 in VS2019 ,it report :
4>Traceback (most recent call last):
4>  File "F:\gpufit\gpufit_build\Release\pyCpufit\setup.py", line 10, in <module>
4>    import pycpufit.version as vs
4>  File "F:\gpufit\gpufit_build\Release\pyCpufit\pycpufit\__init__.py", line 1, in <module>
4>    from cpufit import *
4>ModuleNotFoundError: No module named 'cpufit'
4>D:\VS2019\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: “F:\gpufit\gpufit_...
 
this is the only error report. other project building completed well.

**Comment by sudb92** [comment]
Commenting out the 'from cpufit import *' in Cpufit/python/pycpufit/__init__.py helped me build it without error. When running example programs replace the line 'import cpufit as cf' with 'import pycpufit.cpufit as cf'. YMMV.

**Comment by Nikongen** [comment]
@superchromix This issue can be closed as solved with https://github.com/gpufit/Gpufit/pull/130
